### ISSUE TITLE
Languages Text 

### ISSUE THREAD

**Issue by eravse** [ChendrayanV/Office365-Resume-Builder-Addin#1]
At the bottom of the information may be a structure that we can use long names.

en-us  = English 
tr-tr = Turkish etc.

**Comment by ChendrayanV** [comment]
Great! Thanks, will fix it!

**Comment by ChendrayanV** [comment]
selection.TypeText(string.Concat("Languages", "\t", "\t", selection.Text = CultureInfo.GetCultureInfo(Languages.Split(',')[0]).DisplayName));

Shows the first language as main language (Priority)
